---
title: "AnalysisR2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages(ggplot2)
install.packages(dplyr)
setwd("M:/PhD/Project/Experiment_Code/Straights") # set working directory
temp = list.files(pattern = "*.csv") # list all CSV files in the directory
myfiles = lapply(temp, read.csv) # read these CSV in the directory
workingdata <- do.call(rbind.data.frame, myfiles) # convert and combine the CSV files into dataframe
```

```{r cleaning }

library(dplyr)

pilot_clean <- subset(workingdata, select = c(ppid, heading, cameraoffset, trialn, timestamp, World_x, World_z, WorldYaw, SWA, YawRate_seconds)) # selects important data columns

View(pilot_clean)

deadzone <- 0.01

pilot <- pilot_clean %>%
  group_by(trialn) %>%
  filter(first(abs(SWA) > deadzone))

View(pilot)

```

```{r code dump for trying to calculate time until first steering correction}

# split_trials <- split(pilot_clean, pilot_clean$trialn) # create a new data frame split by trials

# trialn1 <- pilot_clean_new[[2]][5] - head(split_trials[[2]][5], n = 1)
# trialn2 <- pilot_clean_new[[3]][5] - head(split_trials[[3]][5], n = 1)
# trialn3 <- pilot_clean_new[[4]][5] - head(split_trials[[4]][5], n = 1)
# trialn4 <- pilot_clean_new[[5]][5] - head(split_trials[[5]][5], n = 1)
# trialn5 <- pilot_clean_new[[6]][5] - head(split_trials[[6]][5], n = 1)
# trialn6 <- pilot_clean_new[[7]][5] - head(split_trials[[7]][5], n = 1)
# trialn7 <- pilot_clean_new[[8]][5] - head(split_trials[[8]][5], n = 1)
# trialn9 <- pilot_clean_new[[10]][5] - head(split_trials[[10]][5], n = 1)
# trialn10 <- pilot_clean_new[[11]][5] - head(split_trials[[11]][5], n = 1)
# trialn11 <- pilot_clean_new[[12]][5] - head(split_trials[[12]][5], n = 1)
# trialn12 <- pilot_clean_new[[13]][5] - head(split_trials[[13]][5], n = 1)
# trialn13 <- pilot_clean_new[[14]][5] - head(split_trials[[14]][5], n = 1)
# trialn14 <- pilot_clean_new[[15]][5] - head(split_trials[[15]][5], n = 1)
# trialn15 <- pilot_clean_new[[16]][5] - head(split_trials[[16]][5], n = 1)
# trialn16 <- pilot_clean_new[[17]][5] - head(split_trials[[17]][5], n = 1)
# trialn17 <- pilot_clean_new[[18]][5] - head(split_trials[[18]][5], n = 1)
# trialn18 <- pilot_clean_new[[19]][5] - head(split_trials[[19]][5], n = 1)
# trialn19 <- pilot_clean_new[[20]][5] - head(split_trials[[20]][5], n = 1)
# trialn20 <- pilot_clean_new[[21]][5] - head(split_trials[[21]][5], n = 1)
# trialn21 <- pilot_clean_new[[22]][5] - head(split_trials[[22]][5], n = 1)
# trialn22 <- pilot_clean_new[[23]][5] - head(split_trials[[23]][5], n = 1)
# 
# # Above code selects first timestamp once SWA has gone above threshold and then subtract the timestamp at the start of the trial to get the time for the first steering adjustment
# 
# FirstSteeringTime <- c(trialn1, trialn2, trialn3, trialn4, trialn5, trialn6, trialn7, trialn9, trialn10, trialn11, trialn12, trialn13, trialn14, trialn15, trialn16, trialn17, trialn18, trialn19, trialn20, trialn21, trialn22) # put trial times in a data columns
# 
# # Convert list back to dataframes
# FirstSteeringTime <- do.call(rbind.data.frame, FirstSteeringTime)
# names(FirstSteeringTime) <- c("firststeeringtime")
# 
# pilot_clean_new <- do.call(rbind.data.frame, pilot_clean_new)
# 
# clean_data <- cbind.data.frame(pilot_clean_new, FirstSteeringTime) # combine dataframes
# 
# View(clean_data)

```
