---
title: "AnalysisRNew"
output: 
  html_document:
    self_contained: no
---

```{r setup, echo=TRUE}
# chooseCRANmirror(graphics=FALSE, ind=1)
knitr::opts_chunk$set(echo = TRUE)
install.packages(ggplot2)
install.packages(dplyr)
# install.packages("magrittr")
setwd("M:/PhD/Project/Experiment_Code/Straights") # set working directory
temp = list.files(pattern = "*.csv") # list all CSV files in the directory
myfiles = lapply(temp, read.csv) # read these CSV in the directory
workingdata <- do.call(rbind.data.frame, myfiles) # convert and combine the CSV files into dataframe
```

```{r cleaning, echo=TRUE}

# install.packages("magrittr")
# setwd("M:/PhD/Project/Experiment_Code/Straights")
# mydata = read.csv("BenLui17_2.csv")

# library(magrittr)
library(dplyr)
# deadzone threshold
SWA_threshold = 0.01

 example <- mydata$YawRate_seconds - c(0,mydata$YawRate_seconds[-length(mydata$YawRate_seconds)]) # this will actually work

workingdata <- mydata %>%
  mutate(idx=row_number(YawRate_seconds))

workingdata <- left_join(workingdata, workingdata %>% 
                           mutate(idx=idx+1), by='idx')

workingdata<- workingdata %>% 
  mutate(lag_diff=YawRate_seconds.x-YawRate_seconds.y) %>% select(YawRate_seconds=YawRate_seconds.x, lag_diff)


# determine first time in each ppid for each trialn
first_time <- workingdata %>%
  group_by(ppid,trialn) %>% 
  filter(row_number() == 1) %>% 
  ungroup()  %>% 
  transmute(ppid, heading, trialn, cameraoffset, SWAStart = SWA, TrialStart = timestamp, StartWorld_x = World_x, StartWorld_z = World_z, StartWorldYaw = WorldYaw, StartYawRate_seconds = YawRate_seconds) #use transmute to rename nwly computed variable (TrialStart) future join, ungroup first to allow for column rename of grouping variable

# determine first time in each ppid, trialn group above threshold
threshold <-workingdata %>%
  group_by(ppid,trialn) %>%
  filter(abs(SWA) > SWA_threshold) %>%
  filter(row_number() == 1) %>%
  ungroup() %>%
  transmute(ppid, heading, trialn, cameraoffset, SWAThres = SWA, FirstSWATimeThres = timestamp, ThresWorld_x = World_x, ThresWorld_z = World_z, ThresWorldYaw = WorldYaw, ThresYawRate_seconds = YawRate_seconds) #use transmute to rename for future join, ungroup first to allow for column rename of grouping variable

# produce final result set with ppid, trialn, first time, and first time above threshold
workingdatafinal <- left_join(first_time, threshold, by = c("ppid", "heading", "cameraoffset", "trialn")) %>%
  mutate(FirstSteeringTime = FirstSWATimeThres - TrialStart) # calculate final result

```

```{r plotting positive angles, echo=TRUE}

library(ggplot2)
library(dplyr)

positive_offset <- workingdatafinal %>%
  filter(heading >= 0, FirstSteeringTime > 0) # creates dataframe with only positive angle offsets and removes trials where SWA was already above threshold at the start of the time

# input FirstSteeringTime > 0.2 & FirstSteeringTime < 1.6 to remove outliers

ggplot(positive_offset, aes(x = heading, y = FirstSteeringTime)) +
  geom_jitter() +
  geom_smooth() +
  ggtitle("First steering time across heading angles") +
  xlab("Heading angle (degrees)") +
  ylab("Time until first steering correction (s)")

ggplot(positive_offset, aes(as.factor(heading), FirstSteeringTime)) +
  geom_boxplot() +
  ggtitle("First steering time across heading angles: boxplots") +
  xlab("Heading angle (degrees)") +
  ylab("Time until first steering correction (s)")

```

```{r plotting negative offsets, echo=TRUE}

library(ggplot2)
library(dplyr)

negative_offset <- workingdatafinal %>%
  filter(heading <= 0, FirstSteeringTime > 0)
  # creates dataframe with only positive angle offsets and removes trials where SWA was already above threshold at the start of the time

# input FirstSteeringTime > 0.2 & FirstSteeringTime < 1.3 to remove outliers

ggplot(negative_offset, aes(x = heading, y = FirstSteeringTime)) +
  geom_jitter() +
  geom_smooth() +
  ggtitle("First steering time across heading angles") +
  xlab("Heading angle (degrees)") +
  ylab("Time until first steering correction (s)")

ggplot(negative_offset, aes(as.factor(heading), FirstSteeringTime)) +
  geom_boxplot() +
  ggtitle("First steering time across heading angles: boxplots") +
  xlab("Heading angle (degrees)") +
  ylab("Time until first steering correction (s)")


```

```{r mean and median values, echo=TRUE}

library(dplyr)

# calculating mean and median first steering timings for eaching heading offset

# negative offset

negative_offset %>%
  group_by(heading) %>%
  summarise(meanFirstSteering = mean(FirstSteeringTime, na.rm = TRUE))

negative_offset %>%
  group_by(heading) %>%
  summarise(medianFirstSteering = median(FirstSteeringTime, na.rm = TRUE))

# positive offset

positive_offset %>%
  group_by(heading) %>%
  summarise(meanFirstSteering = mean(FirstSteeringTime, na.rm = TRUE))

positive_offset %>%
  group_by(heading) %>%
  summarise(medianFirstSteering = median(FirstSteeringTime, na.rm = TRUE))

```



