---
title: "AnalysisRNewThreshold_Timestamp"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# chooseCRANmirror(graphics=FALSE, ind=1) # uncomment for knitting
# rm(list = ls()) # clear workspace
install.packages(ggplot2)
install.packages(dplyr)
install.packages(tidyr)
install.packages(TTR)
install.packages(zoo)
# install.packages("magrittr")
setwd("M:/PhD/Project/Experiment_Code/Straights") # set working directory
temp = list.files(pattern = "*.csv") # list all CSV files in the directory
myfiles = lapply(temp, read.csv) # read these CSV in the directory
workingdata <- do.call(rbind.data.frame, myfiles) # convert and combine the CSV files into dataframe
```

```{r thresholds, clipping data, calculating yaw rate change, removing spikes}
library(tidyr)
library(dplyr)

# change in steering threshold
upperthreshold = 0.105 # 0.2184 # upper threshold for consistent steering response
lowerthreshold = 0.010 # lower threshold for when response initiated 

workingdata <- unite(workingdata, ppid_trialn, ppid, trialn, sep = "_") # create unique ppid_trialn ID

workingdata <- workingdata %>%
  group_by(ppid_trialn) %>% 
  arrange(timestamp) %>% 
  slice(1:266) %>%
  mutate(anchored_timestamp = linspace(0, 4, 266)) %>%
  ungroup() %>%
  mutate(YawRateChange = YawRate_seconds - c(0, YawRate_seconds[-length(YawRate_seconds)])) # calculating difference in yawrate

```

```{r formulating threshold data}
library(zoo)
library(dplyr)
library(tidyr)
library(TTR)

workingdatathresholdUnsmooth <- workingdata %>%
  group_by(ppid_trialn)%>%
  mutate(row_number())%>% # added to verify selection
  filter(max(abs(YawRateChange)) > upperthreshold, # filter largest yaw rate change greater than the upper threshold
         min(abs(YawRateChange)) < lowerthreshold) %>% # filter lowest yaw rate change smaller than the lower theshold
  slice(1:min(which(abs(YawRateChange) > upperthreshold))) %>% 
  slice(max(which(abs(YawRateChange) < lowerthreshold))) %>% # which() returns rows where a condition is true. Taking the min() of all the rows that are greater than the criteria will return the first row where that is true.
  ungroup() %>%
  transmute(ppid_trialn, heading, cameraoffset, SWAThres = SWA, FirstSteeringTime = anchored_timestamp, ThresWorld_x = World_x, ThresWorld_z = World_z, ThresWorldYaw = WorldYaw, ThresYawRate_seconds = YawRate_seconds, ThresYawRateChange = YawRateChange)

##################################### SMOOTHING DATA ###################################

# workingdatatimecourseSmooth <- workingdatatimecourseUnsmooth %>%
#   mutate(smoothedYawRateChange = SMA(YawRateChange, n = 1)) # calculates moving average over the number of data points you specify
# 
# workingdatatimecourseSmooth[is.na(workingdatatimecourseSmooth)] <- 0 # set NA values to 0. This is because smoothing data in this way creates NA values if you don't have enough to average over. Unsure how else to get around this
# 
# # determine first time in each ppid, trialn group above threshold
# workingdatathresholdSmooth <- workingdatatimecourseSmooth %>%
#   group_by(ppid_trialn)%>%
#   mutate(row_number())%>% # added to verify selection
#   filter(max(abs(smoothedYawRateChange)) > upperthreshold, # filter largest yaw rate change greater than the upper threshold
#          min(abs(smoothedYawRateChange)) < lowerthreshold) %>% # filter lowest yaw rate change smaller than the lower theshold
#   slice(1:min(which(abs(smoothedYawRateChange) > upperthreshold))) %>%
#   slice(max(which(abs(smoothedYawRateChange) < lowerthreshold))) %>% # which() returns rows where a condition is true. Taking the min() of all the rows that are greater than the criteria will return the first row where that is true.
#   ungroup() %>%
#   transmute(ppid_trialn, heading, cameraoffset, SWAThres = SWA, FirstSteeringTime = anchored_timestamp, ThresWorld_x = World_x, ThresWorld_z = World_z, ThresWorldYaw = WorldYaw, ThresYawRate_seconds = YawRate_seconds, ThresYawRateChange = smoothedYawRateChange)

##################################### SMOOTHING DATA ###################################

# Here SWA angle is redundent as it only takes the SWA for when the change in yaw rate is over the threshold... I'm interested in ThresYawRateChange (first change in yaw rate over threhsold) and FirstYawRateChangeTimeThres (first timestamp where yaw rate change is over threshold).

#Only thing extra would be to calculate frame rate (60 frames) (ask Richard), and then multiply by change in yaw rate to get yaw rate per second per second.

```


```{r timecourse plotting of yaw rate change}
library(ggplot2)
library(dplyr)

# workingdatathreshold <- workingdatathreshold %>%
  # filter(FirstSteeringTime < 1.25) # filter outliers 

######## -2 heading ##########

ggplot(data = filter(workingdata, heading == -2), aes(x = anchored_timestamp, y = YawRateChange, colour = ppid_trialn)) +
  geom_line() +
  geom_vline(data = filter(workingdatathresholdUnsmooth, heading == -2) %>%
               summarise(meanFirstSteeringTime = mean(FirstSteeringTime, na.rm = TRUE)), aes(xintercept = meanFirstSteeringTime)) +
  ggtitle("-2 heading - unsmoothed") +
  scale_y_continuous(limits = c(-0.50, 0.75))

# ggplot(data = filter(workingdatatimecourseSmooth, heading == -2), aes(x = anchored_timestamp, y = YawRateChange, colour = ppid_trialn)) +
#   geom_line() +
#   geom_vline(data = filter(workingdatathresholdSmooth, heading == -2) %>%
#                summarise(meanFirstSteeringTime = mean(FirstSteeringTime, na.rm = TRUE)), aes(xintercept = meanFirstSteeringTime)) +
#   ggtitle("-2 heading - smoothed") +
#   scale_y_continuous(limits = c(-0.50, 0.75))

######## -1 heading ##########

ggplot(data = filter(workingdata, heading == -1), aes(x = anchored_timestamp, y = YawRateChange, colour = ppid_trialn)) +
  geom_line() +
  geom_vline(data = filter(workingdatathresholdUnsmooth, heading == -1) %>%
               summarise(meanFirstSteeringTime = mean(FirstSteeringTime, na.rm = TRUE)), aes(xintercept = meanFirstSteeringTime)) +
  ggtitle("-1 heading - unsmoothed") +
  scale_y_continuous(limits = c(-0.50, 0.75))

# ggplot(data = filter(workingdatatimecourseSmooth, heading == -1), aes(x = anchored_timestamp, y = YawRateChange, colour = ppid_trialn)) +
#   geom_line() +
#   geom_vline(data = filter(workingdatathresholdSmooth, heading == -1) %>%
#                summarise(meanFirstSteeringTime = mean(FirstSteeringTime, na.rm = TRUE)), aes(xintercept = meanFirstSteeringTime)) +
#   ggtitle("-1 heading - smoothed") +
#   scale_y_continuous(limits = c(-0.50, 0.75))

######## 0 heading ##########

ggplot(data = filter(workingdata, heading == 0), aes(x = anchored_timestamp, y = YawRateChange, colour = ppid_trialn)) +
  geom_line() +
  geom_vline(data = filter(workingdatathresholdUnsmooth, heading == 0) %>%
               summarise(meanFirstSteeringTime = mean(FirstSteeringTime, na.rm = TRUE)), aes(xintercept = meanFirstSteeringTime)) +
  ggtitle("0 heading - unsmoothed") +
  scale_y_continuous(limits = c(-0.50, 0.75))

# ggplot(data = filter(workingdatatimecourseSmooth, heading == 0), aes(x = anchored_timestamp, y = YawRateChange, colour = ppid_trialn)) +
#   geom_line() +
#   geom_vline(data = filter(workingdatathresholdSmooth, heading == 0) %>%
#                summarise(meanFirstSteeringTime = mean(FirstSteeringTime, na.rm = TRUE)), aes(xintercept = meanFirstSteeringTime)) +
#   ggtitle("0 heading - smoothed") +
#   scale_y_continuous(limits = c(-0.50, 0.75))

######## +1 heading ##########

ggplot(data = filter(workingdata, heading == 1), aes(x = anchored_timestamp, y = YawRateChange, colour = ppid_trialn)) +
  geom_line() +
  geom_vline(data = filter(workingdatathresholdUnsmooth, heading == 1) %>%
               summarise(meanFirstSteeringTime = mean(FirstSteeringTime, na.rm = TRUE)), aes(xintercept = meanFirstSteeringTime)) +
  ggtitle("+1 heading - unsmoothed") +
  scale_y_continuous(limits = c(-0.50, 0.75))

# ggplot(data = filter(workingdatatimecourseSmooth, heading == 1), aes(x = anchored_timestamp, y = YawRateChange, colour = ppid_trialn)) +
#   geom_line() +
#   geom_vline(data = filter(workingdatathresholdSmooth, heading == 1) %>%
#                summarise(meanFirstSteeringTime = mean(FirstSteeringTime, na.rm = TRUE)), aes(xintercept = meanFirstSteeringTime)) +
#   ggtitle("+1 heading - smoothed") +
#   scale_y_continuous(limits = c(-0.50, 0.75))

######## +2 heading ##########

ggplot(data = filter(workingdata, heading == 2), aes(x = anchored_timestamp, y = YawRateChange, colour = ppid_trialn)) +
  geom_line() +
  geom_vline(data = filter(workingdatathresholdUnsmooth, heading == 2) %>%
               summarise(meanFirstSteeringTime = mean(FirstSteeringTime, na.rm = TRUE)), aes(xintercept = meanFirstSteeringTime)) +
  ggtitle("+2 heading - unsmoothed") +
  scale_y_continuous(limits = c(-0.50, 0.75))

# ggplot(data = filter(workingdatatimecourseSmooth, heading == 2), aes(x = anchored_timestamp, y = YawRateChange, colour = ppid_trialn)) +
#   geom_line() +
#   geom_vline(data = filter(workingdatathresholdSmooth, heading == 2) %>%
#                summarise(meanFirstSteeringTime = mean(FirstSteeringTime, na.rm = TRUE)), aes(xintercept = meanFirstSteeringTime)) +
#   ggtitle("+2 heading - smoothed") +
#   scale_y_continuous(limits = c(-0.50, 0.75))

```


```{r timecourse plotting for individual trials}
library(ggplot2)
library(dplyr)

##### -2 ######

ggplot(data = filter(workingdata, heading == -2), aes(x = anchored_timestamp, y = YawRateChange)) +
  geom_line() +
  geom_vline(data = filter(workingdatathresholdUnsmooth, heading == -2), aes(xintercept = FirstSteeringTime), col = "red") +
  facet_wrap( ~ ppid_trialn) +
  scale_y_continuous(limits = c(-0.60, 0.80)) +
  ggtitle("-2 heading - unsmoothered")

# ggplot(data = filter(workingdatatimecourseSmooth, heading == -2), aes(x = anchored_timestamp, y = smoothedYawRateChange)) +
#   geom_line() +
#   geom_vline(data = filter(workingdatathresholdSmooth, heading == -2), aes(xintercept = FirstSteeringTime), col = "red") +
#   facet_wrap( ~ ppid_trialn) +
#   scale_y_continuous(limits = c(-0.60, 0.80)) +
#   ggtitle("-2 heading - smoothered")

##### -1 ######

ggplot(data = filter(workingdata, heading == -1), aes(x = anchored_timestamp, y = YawRateChange)) +
  geom_line() +
  geom_vline(data = filter(workingdatathresholdUnsmooth, heading == -1), aes(xintercept = FirstSteeringTime), col = "red") +
  facet_wrap( ~ ppid_trialn) +
  scale_y_continuous(limits = c(-0.60, 0.80)) +
  ggtitle("-1 heading - unsmoothered")

# ggplot(data = filter(workingdatatimecourseSmooth, heading == -1), aes(x = anchored_timestamp, y = smoothedYawRateChange)) +
#   geom_line() +
#   geom_vline(data = filter(workingdatathresholdSmooth, heading == -1), aes(xintercept = FirstSteeringTime), col = "red") +
#   facet_wrap( ~ ppid_trialn) +
#   scale_y_continuous(limits = c(-0.60, 0.80)) +
#   ggtitle("-1 heading - smoothered")

#### 0 ########

ggplot(data = filter(workingdata, heading == 0), aes(x = anchored_timestamp, y = YawRateChange)) +
  geom_line() +
  geom_vline(data = filter(workingdatathresholdUnsmooth, heading == 0), aes(xintercept = FirstSteeringTime), col = "red") +
  facet_wrap( ~ ppid_trialn) +
  scale_y_continuous(limits = c(-0.60, 0.80)) +
  ggtitle("0 heading - unsmoothed")

# ggplot(data = filter(workingdatatimecourseSmooth, heading == 0), aes(x = anchored_timestamp, y = smoothedYawRateChange)) +
#   geom_line() +
#   geom_vline(data = filter(workingdatathresholdSmooth, heading == 0), aes(xintercept = FirstSteeringTime), col = "red") +
#   facet_wrap( ~ ppid_trialn) +
#   scale_y_continuous(limits = c(-0.60, 0.80)) +
#   ggtitle("0 heading - smoothed")

###### +1 ######

ggplot(data = filter(workingdata, heading == 1), aes(x = anchored_timestamp, y = YawRateChange)) +
  geom_line() +
  geom_vline(data = filter(workingdatathresholdUnsmooth, heading == 1), aes(xintercept = FirstSteeringTime), col = "red") +
  facet_wrap( ~ ppid_trialn) +
  scale_y_continuous(limits = c(-0.60, 0.80)) +
  ggtitle("+1 heading - unsmoothed")

# ggplot(data = filter(workingdatatimecourseSmooth, heading == 1), aes(x = anchored_timestamp, y = smoothedYawRateChange)) +
#   geom_line() +
#   geom_vline(data = filter(workingdatathresholdSmooth, heading == 1), aes(xintercept = FirstSteeringTime), col = "red") +
#   facet_wrap( ~ ppid_trialn) +
#   scale_y_continuous(limits = c(-0.60, 0.80)) +
#   ggtitle("+1 heading - smoothed")

##### +2 #####

ggplot(data = filter(workingdata, heading == 2), aes(x = anchored_timestamp, y = YawRateChange)) +
  geom_line() +
  geom_vline(data = filter(workingdatathresholdUnsmooth, heading == 2), aes(xintercept = FirstSteeringTime), col = "red") +
  facet_wrap( ~ ppid_trialn) +
  scale_y_continuous(limits = c(-0.60, 0.80)) +
  ggtitle("+2 heading - unsmoothed")

# ggplot(data = filter(workingdatatimecourseSmooth, heading == 2), aes(x = anchored_timestamp, y = smoothedYawRateChange)) +
#   geom_line() +
#   geom_vline(data = filter(workingdatathresholdSmooth, heading == 2), aes(xintercept = FirstSteeringTime), col = "red") +
#   facet_wrap( ~ ppid_trialn) +
#   scale_y_continuous(limits = c(-0.60, 0.80)) +
#   ggtitle("+2 heading - smoothed")

```