---
title: "demographic_code"
output: html_document
---

```{r load data, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# rm(list = ls()) # clear environment

# load data

setwd("C:/Users/pscmgo/OneDrive for Business/PhD/Project/Experiment_Code/Straights") # set working directory
# setwd("C:/Users/Courtney/Documents/PhD/Project/Experiment_code/Straights")
temp = list.files(pattern = c("BenLui17_19", "*.csv")) # list all CSV files in the directory
myfiles = lapply(temp, read.csv) # read these CSV in the directory
workingdata <- do.call(rbind.data.frame, myfiles) # convert and combine the CSV files into dataframe

```

load in each block one at a time

```{r create new block variable}
library(dplyr)

###### for block 1 dataframes
workingdata <- workingdata %>%
  mutate(block = "first") %>%
  mutate(pNum = 15)




###### for block 2 dataframes
workingdataFirst <- workingdata %>%
  dplyr::filter(trialn <= 45) %>%
  mutate(block = "first") %>%
  mutate(pNum = 15)

workingdataSecond <- workingdata %>%
  dplyr::filter(trialn > 45) %>%
  mutate(block = "second") %>%
  mutate(pNum = 15)

workingdata <- rbind(workingdataFirst, workingdataSecond)



####### for block 3 dataframes
workingdata <- workingdata %>%
  mutate(block = "second") %>%
  mutate(pNum = 15)


```

create new block variable

```{r saving first/second half datadframe}

setwd("C:/Users/Courtney/Documents/PhD/Project/Experiment_code/Straights/test_example") # set directory for data saving
write.csv(workingdata, file = "BenLui17_15_3.csv") # save the same name but in a different place

```

save block dataframe as the same name but in a different place. Do this for 3 blocks x 3 participants

```{r load in all 3 blocks for each of the 3 test participant}

# rm(list = ls()) # clear environment

# load data

# setwd("C:/Users/pscmgo/OneDrive for Business/PhD/Project/Experiment_Code/Straights/test_example") # set working directory
setwd("C:/Users/Courtney/Documents/PhD/Project/Experiment_code/Straights/test_example")
temp = list.files(pattern = c("BenLui17_15", "*.csv")) # list all CSV files in the directory
myfiles = lapply(temp, read.csv) # read these CSV in the directory
workingdata <- do.call(rbind.data.frame, myfiles) # convert and combine the CSV files into dataframe

```

load in 3 blocks and combine them but no point creating demographioc columns for data I'm doing

```{r saving new combined data frame}

setwd("C:/Users/Courtney/Documents/PhD/Project/Experiment_code/Straights/test_example/Full_Data") # set directory for data saving
write.csv(workingdata, file = "BenLui17_15_full.csv")

```

save new full dataset into the test folder















*BELOW IS FOR ORDINARY DATA, ABOVE IS A TEST FOR 3 PARTICIPANTS*

```{r adding demographic information to data frame}
library(dplyr)

workingdata <- workingdata %>%
  group_by(trialn) %>%
  mutate(gender = 1, age = 38, licenseTime = 264, contacts_glasses = TRUE, pNum = 19, handedness = 1) %>% # female = 1, male = 2; license time in months; right = 1, left = 2
  ungroup()

```

```{r saving new combined data frame}

setwd("C:/Users/pscmgo/OneDrive for Business/PhD/Project/Experiment_Code/Straights/Full_Data") # set directory for data saving
write.csv(workingdata, file = "BenLui17_19_full.csv")

```

