---
title: "plotting timecourse"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages(ggplot2)
install.packages(dplyr)
install.packages(tidyr)
install.packages(matlab)
# install.packages("magrittr")
setwd("C:/Users/Courtney/Documents/PhD/Project/Experiment_code/Straights") # set working directory
temp = list.files(pattern = "*.csv") # list all CSV files in the directory
myfiles = lapply(temp, read.csv) # read these CSV in the directory
workingdata <- do.call(rbind.data.frame, myfiles) # convert and combine the CSV files into dataframe
```

```{r creating dataframe and yaw rate change variables}

library(dplyr)

# change in steering threshold
yawratechange_threshold = 0.1

YRchange <- workingdata$YawRate_seconds - c(0,workingdata$YawRate_seconds[-length(workingdata$YawRate_seconds)]) # calculating difference in yawrate

YRchange <- data.frame(YRchange) # convert yaw rate to dataframe

colnames(YRchange) <- c("YawRateChange") # change column names

workingdata <- cbind(workingdata, YRchange) # join dataframes

# determine first time in each ppid for each trialn
first_time <- workingdata %>%
  group_by(ppid,trialn) %>% 
  filter(row_number() == 1) %>% 
  ungroup()  %>% 
  transmute(ppid, heading, trialn, cameraoffset, SWAStart = SWA, TrialStart = timestamp, StartWorld_x = World_x, StartWorld_z = World_z, StartWorldYaw = WorldYaw, StartYawRate_seconds = YawRate_seconds, StartYawRateChange = YawRateChange) #use transmute to rename nwly computed variable (TrialStart) future join, ungroup first to allow for column rename of grouping variable

# determine first time in each ppid, trialn group above threshold 
threshold <-workingdata %>%
  group_by(ppid,trialn) %>%
  filter(abs(YawRateChange) > yawratechange_threshold) %>%
  filter(row_number() == 1) %>%
  ungroup() %>%
  transmute(ppid, heading, trialn, cameraoffset, SWAThres = SWA, FirstYawRateChangeTimeThres = timestamp, ThresWorld_x = World_x, ThresWorld_z = World_z, ThresWorldYaw = WorldYaw, ThresYawRate_seconds = YawRate_seconds, ThresYawRateChange = YawRateChange) #use transmute to rename for future join, ungroup first to allow for column rename of grouping variable

# Here SWA angle is redundent as it only takes the SWA for when the change in yaw rate is over the threshold... I'm interested in ThresYawRateChange (first change in yaw rate over threhsold) and FirstYawRateChangeTimeThres (first timestamp where yaw rate change is over threshold).

# produce final result set with ppid, trialn, first time, and first time above yaw rate change threshold
workingdatafinal <- left_join(first_time, threshold, by = c("ppid", "heading", "cameraoffset", "trialn")) %>%
  mutate(FirstSteeringTime = FirstYawRateChangeTimeThres - TrialStart) # calculate final result: first timestamp where change in yaw rate is over threshold minus starting trial timestamp

#Only thing extra would be to calculate frame rate (60 frames per second) (ask Richard), and then multiply by change in yaw rate to get yaw rate per second per second.

```

```{r filtering for heading and selecting 4 seconds of data}
library(ggplot2)
library(dplyr)
library(tidyr)

minus1 <- workingdata %>%
  filter(heading < 0 & heading > -2)

minus1data <-  minus1 %>% 
  group_by(ppid, trialn) %>%
  filter(timestamp<=min(timestamp)+4) %>%
  ungroup() # filters data so only first 4 seconds from the start of the trial is selected

minus1data <- unite(minus1data, ppid_trialn, ppid, trialn, sep = "_") # creating uniuqe ID for participants and trials

minus1data <- minus1data %>%
  group_by(ppid_trialn) %>%
  mutate(anchored_timestamp = timestamp - min(timestamp)) # creating new variable of 4 second data in order to plot everything on top of each other

```

```{r plotting all timecourses}
library(ggplot2)
library(dplyr)

ggplot(data = minus1data, aes(x = anchored_timestamp, y = YawRateChange, colour = ppid_trialn)) +
  geom_line()


