---
title: "Model comparison"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Loading model parameters into R
setwd("C:/Users/pscmgo/OneDrive for Business/PhD/Project/Experiment_Code/Straights")
ModelMagnitudeValues <- read.csv("ModelMagnitudeValues.csv", header = FALSE) # magnitude data from model sims
ModelRTValues <- read.csv("ModelRTValues.csv", header = FALSE) # RT data from model sims

# Loading human data into R

humanMagnitude <- read.csv("magnitudedata.csv", header = FALSE)
names(humanMagnitude) <- c("heading", "responseStart", "responsePeak", "responseEnd", "YawRateChangeChange", "YawRateChangeTime (frames)")

```

```{r create model dataframes}
library(tidyr)
library(dplyr)

# good way of creating model sim data frames

threshPredicted <- as.data.frame(c(ModelMagnitudeValues[1:4], ModelRTValues[1:4]))

threshPredicted <- threshPredicted %>%
  gather(key = id_obs, value = "value") %>%
  separate(id_obs, into = c("id", "obs"), sep = "\\.") %>%
  mutate(final_colname = if_else(is.na(obs), "threshMagnitude", "threshRT")) %>%
  select(-obs) %>%
  spread(final_colname, value)

threshPredicted[1] <- NULL

accPredicted <- as.data.frame(c(ModelMagnitudeValues[5:8], ModelRTValues[5:8]))

accPredicted <- accPredicted %>%
  gather(key = id_obs, value = "value") %>%
  separate(id_obs, into = c("id", "obs"), sep = "\\.") %>%
  mutate(final_colname = if_else(is.na(obs), "accMagnitude", "accRT")) %>%
  select(-obs) %>%
  spread(final_colname, value)

accPredicted[1] <- NULL

angles <- as.data.frame(c(0.5, 1.0, 1.5, 2.0))
colnames(angles) <- c("angles")

predictedData <- cbind(threshPredicted, accPredicted, angles)
View(predictedData)


###### shit way of creating model sim dataframes ######

# threshPredicted <- matrix(c(ModelMagnitudeValues[1:4], ModelRTValues[1:4]), nrow = 4, ncol = 2)
# colnames(threshPredicted) <- c("threshMagnitude", "threshRT")
# threshPredicted <- as.data.frame(threshPredicted)
# 
# accPredicted <- matrix(c(ModelMagnitudeValues[1:4], ModelRTValues[1:4]), nrow = 4, ncol = 2)
# colnames(accPredicted) <- c("accMagnitude", "accRT")
# accPredicted <- as.data.frame(accPredicted)
# 
# angles <- as.data.frame(c(0.5, 1.0, 1.5, 2.0))
# colnames(angles) <- c("angles")
# 
# predictedData <- cbind(threshPredicted, accPredicted, angles)

###### shit way of creating model sim dataframes ######

```

```{r add human data to predicted data}
library(tidyr)
library(dplyr)
library(ggplot2)

# combinding predicted data and average human steering RTs

predictedData <- cbind(predictedData, avgFirstSteeringTimes)

# collpasing magnitude data across headings

humanMagnitude <- humanMagnitude %>%
  mutate(heading = abs(heading), responseStart = abs(responseStart), responsePeak = abs(responsePeak), responseEnd = abs(responseEnd), YawRateChangeChange = abs(YawRateChangeChange)) %>%
  group_by(heading) %>%
  summarise(responseStart = mean(responseStart), responsePeak = mean(responsePeak), responseEnd = mean(responseEnd), YawRateChangeChange = mean(YawRateChangeChange), `YawRateChangeTime (frames)` = mean(`YawRateChangeTime (frames)`))

predictedData <- cbind(predictedData, humanMagnitude[3])

```

```{r linear model for comparing thresh and acc MAGNITUDE DATA}

# threshold model versus human data
threshmodelComp <- lm(responsePeak ~ threshMagnitude, predictedData) # creates linear model comparing threshold and human data magnitudes

plot(predict(threshmodelComp), predictedData$responsePeak, xlab = "predicted", ylab = "actual")
abline(a = 0, b = 1)

summary(threshmodelComp)
AIC(threshmodelComp)
logLik(threshmodelComp)

# accumulator versus human data

accmodelComp <- lm(responsePeak ~ accMagnitude, predictedData) # creates linear model comparing threshold and human data magnitudes

plot(predict(accmodelComp), predictedData$responsePeak, xlab = "predicted", ylab = "actual")
abline(a = 0, b = 1)

summary(accmodelComp)
AIC(accmodelComp)
logLik(accmodelComp)

```


```{r linear model for comparing thresh and acc RT DATA}

# threshold model versus human data
threshmodelCompRT <- lm(humanRTdata ~ threshRT, predictedData) # creates linear model comparing threshold and human data magnitudes

plot(predict(threshmodelCompRT), predictedData$humanRTdata, xlab = "predicted", ylab = "actual")
abline(a = 0, b = 1)

summary(threshmodelCompRT)

AIC(threshmodelCompRT)
logLik(threshmodelCompRT)

# accumulator model versus human data

accmodelCompRT <- lm(humanRTdata ~ accRT, predictedData) # creates linear model comparing threshold and human data magnitudes

plot(predict(accmodelCompRT), predictedData$humanRTdata, xlab = "predicted", ylab = "actual")
abline(a = 0, b = 1)

summary(accmodelCompRT)
AIC(accmodelCompRT)
logLik(accmodelCompRT)

```


```{r creating long dataframes}
library(tidyr)

# code below creates long data frames for magnitude and RT data

data_long_RT <- gather(predictedData, key = "datatype", value = "FirstSteeringTime", threshRT, accRT, humanRTdata)
data_long_RT[1:2] <- NULL

data_long_mag <- gather(predictedData, key = "datatype", value = "Magnitude", threshMagnitude, accMagnitude, responsePeak)
data_long_mag[2] <- NULL

ggplot(data = data_long_RT, aes(x = angles, y = FirstSteeringTime, color = datatype)) +
  geom_point() +
  geom_line()

```
