---
title: "anova_sim"
output: html_document
---

```{r setup, include=FALSE}
# rm(list = ls()) # clear workspace
knitr::opts_chunk$set(echo = TRUE)
install.packages(plyr) # apply a function to each subset of the df and save as new df
install.packages(ggplot2)# plotting
install.packages(dplyr) # data manipulation
install.packages(psych) # simulating anova data
install.packages(car) # anova analysis
install.packages(ggpubr) # interaction plots
```

```{r simulate data}
library(psych)

# Steering magnitude simulation 

df <- sim.anova(es1 = 0.9, n1 = 3, factors = TRUE, std = TRUE) # 1 IV, 3 levels

DV <- c(0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4)
IV1 <- c(-1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1)
df2 <- data.frame(IV1, DV)

# First steering reaction time simulation

# df <- sim.anova(es1 = -0.8, n1 = 3, factors = TRUE, std = TRUE) # 1 IV, 3 levels
# 
# DV <- c(0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3)
# IV1 <- c(-1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1)
# df <- data.frame(IV1, DV)
# 
# DV2 <- c(0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1)
# IV1 <- c(-1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1)
# df2 <- data.frame(IV1, DV2)

# df$IV1 <- as.character(df$IV1)
# df$IV1[df$IV1 == 1] <- as.character(1.5)
# df$IV1[df$IV1 == 0] <- as.character(1)
# df$IV1[df$IV1 == -1] <- as.character(0.5)
# df$IV1 <- as.integer(df$IV1)

# View(df)
```

```{r analyse anova sim data}
library(car)

anova <- aov(DV ~ IV1, data = df2)
summary(anova)

resultTukey <- TukeyHSD(anova)
resultTukey
```

```{r interaction plotting}
library(ggplot2)
library(plyr)
library(dplyr)
library(ggpubr) # for interaction plots/boxplots

pAcc <- ggline(df, x = "IV1", y = "DV", add = "mean", color = "red")
ggpar(pAcc, ticks = FALSE, tickslab = FALSE, xlab = c("Rate of change in positional error"), ylab = c("Steering magnitude"), title = c("Accumulation behavioural pattern example for heading offsets 0.5, 1.0 and 1.5"))

pThresh <- ggline(df2, x = "IV1", y = "DV", add = "mean", color = "red")
ggpar(pThresh, ticks = FALSE, tickslab = FALSE, xlab = c("Rate of change in positional error"), ylab = c("Steering magnitude"), title = c("Threshold behavioural pattern example for heading offsets 0.5, 1.0 and 1.5"))

# df_means <- ddply(df,.(IV1), summarise, val = mean(DV)) 
# for IV1 in dataframe df, summarise the DV by calculating mean and save as "val"



```
