---
title: "lateral position computation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r filtering for 2 degree heading condition}

example <- modellingdata %>%
  group_by(heading) %>%
  mutate(predsteeringonset = (1/sin(heading)) * multilevel_slope + multilevel_intercept)

```

**For each heading**
In order to compute time at steering onset from the model parameters, we take the slope value of each subject and multiple by the inverse of the sine of heading and add the intercept:

(Ts)thr = (slope) thr * 1 / sin(heading) + (intercept)thr

```{r averaging steering onset predictions and actual RTS}

example %>%
  group_by(heading) %>%
  summarise(meanRT = mean(FirstSteeringTime), meanpredRT = mean(predsteeringonset))

```

Comparing the predicted steering onset time generated from the model to the actual steering reaction time form the data.

```{r computed lateral position}

example <- example %>%
  mutate(lateralposition = 10 * predsteeringonset * sin(heading))

ggplot(example %>%
  group_by(heading) %>%
  summarise(meanlatpos = mean(lateralposition)), aes(x = heading, y = meanlatpos)) +
  geom_point()

```
